"""new fields in user model

Revision ID: 64305834d8bb
Revises: 5cbb5b0aa3b0
Create Date: 2019-01-24 16:01:28.577197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64305834d8bb'
down_revision = '5cbb5b0aa3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
